# Generated by Django 4.0.7 on 2022-08-12 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pp_gen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='datestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
