# Generated by Django 4.0.6 on 2022-07-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_gen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='ratings',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1),
        ),
    ]
