# Generated by Django 4.0.7 on 2022-08-12 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tc_gen', '0003_company_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='datestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
