# Generated by Django 4.0.7 on 2022-08-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tc_gen', '0004_template_datestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
