# Generated by Django 4.0.6 on 2022-08-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_business_name_alter_profile_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user-circle.png', upload_to='profile/pics'),
        ),
    ]
